// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MvcProgram.Models;

#nullable disable

namespace MvcProgram.Migrations
{
    [DbContext(typeof(ProductContext))]
    [Migration("20250409163250_ContextSrtting")]
    partial class ContextSrtting
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("MvcProgram.Models.Product", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int?>("price")
                        .HasColumnType("INTEGER");

                    b.HasKey("Name");

                    b.ToTable("Product");
                });
#pragma warning restore 612, 618
        }
    }
}
